# Adapted from https://github.com/joblo2213/aoc-badges-action#sample-workflow

name: Update AoC Badges
on:
  schedule:                                      # run workflow based on schedule
    - cron: '11 6 1-25 12 *'                     # from the 1. December till 25. December every day at 6:11

  workflow_dispatch:                             # allow to manually start the workflow

  # push:                                          # (disabled) run on push, be carefull with this setting
  # as the workflow should only be triggered at a rate lower than
  # 4 times a hour to keep traffic on aoc site low
jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2                # clones your repo, make sure the ssh secret is set!
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

      - uses: joblo2213/aoc-badges-action@v2.1
        with:
          userid: 662534                         # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain

      #         Optional inputs:
      #
      #         leaderboard: 'https://adventofcode.com/2020/leaderboard/private/view/00000.json'    # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
      #         file: 'README.md'                                                                   # The file that contains the badges
      #         dayRegex: '(?<=https:\/\/img\.shields\.io\/badge\/day%20ðŸ“…-)[0-9]+(?=-blue)'        # Regular expression that finds the content of the day badge iun your file.
      #         starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20â­-)[0-9]+(?=-yellow)'  # # Regular expression that finds the content of the stars badge iun your file.

      - name: Push changes                        # Step that pushes these local changes back to your github repo
        run: |
          git config --global user.email "<>"
          git config --global user.name "aoc-badges-action"
          git add .
          git diff-index --quiet HEAD || git commit --message "Update badges"
          git push